"""Numbers for manuscript Section 3 (data, states, residuals, screening population), written to DATA_CLAIMS.md.

Companion to 14_locked_claims.py, which covers Sections 4-9. Reads only outputs that already exist:
data/states.csv, out/satellite_summary.csv, out/arrival_sensitivity.csv, out/cadence.csv,
out/residual_summary.csv, out/residual_pairs.csv.gz and data/pair_windows_daily.pkl.gz.

Usage:  py 15_data_claims.py
"""
from __future__ import annotations

import pandas as pd

from common import DATA, OUT, ROOT

SPACING = 20.5
BINS = ["(0, 6]", "(12, 24]", "(24, 48]", "(48, 96]"]


def md_table(df: pd.DataFrame) -> str:
    fmt = lambda v: "" if pd.isna(v) else (f"{v:g}" if isinstance(v, float) else str(v))
    rows = ["| " + " | ".join(map(str, df.columns)) + " |", "|" + "---|" * len(df.columns)]
    rows += ["| " + " | ".join(fmt(v) for v in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join(rows)


def main():
    lines = ["# Data claims for Section 3 (auto-generated by 15_data_claims.py)", ""]
    add = lines.append

    st = pd.read_csv(DATA / "states.csv")
    st["EPOCH"] = pd.to_datetime(st["EPOCH"], utc=True, format="ISO8601")
    sats = pd.read_csv(OUT / "satellite_summary.csv")
    add("## 3.1 Dataset")
    add(f"- Satellites: {sats['NORAD_CAT_ID'].nunique()}; launches: {sats['LAUNCH'].nunique()}; "
        f"element sets after de-duplication: {len(st):,}; first epoch {st['EPOCH'].min():%Y-%m-%d}, last {st['EPOCH'].max():%Y-%m-%d}")
    cad = pd.read_csv(OUT / "cadence.csv", index_col=0)
    for s, r in cad.iterrows():
        add(f"- Cadence, {s}: median gap {r['median_h']:.1f} h, P90 {r['p90_h']:.1f} h, gaps > 24 h {100 * r['frac_gt_24h']:.1f}% (n = {int(r['n']):,})")
    add(f"- Element sets by state: " + ", ".join(f"{k} {v:,}" for k, v in st['STATE'].value_counts().items()))
    add("")

    add("## 3.2 States")
    add(f"- Status at cutoff: " + ", ".join(f"{k} {v}" for k, v in sats['status'].value_counts().items()))
    arr = sats[sats["status"] == "arrived"]
    add(f"- Arrived satellites: days from first element set to arrival median {arr['days_to_arrival'].median():.0f} "
        f"(P10 {arr['days_to_arrival'].quantile(.1):.0f}, P90 {arr['days_to_arrival'].quantile(.9):.0f}); "
        f"drift days median {arr['days_drift'].median():.0f}; ascent days median {arr['days_ascent'].median():.0f}")
    strd = sats[sats["status"] == "stranded"]
    add(f"- Stranded final altitudes: {strd['final_alt'].min():.0f}-{strd['final_alt'].max():.0f} km")
    per = sats.groupby("LAUNCH").agg(n=("status", "size"), arrived=("status", lambda s: (s == "arrived").sum()),
                                     stranded=("status", lambda s: (s == "stranded").sum()),
                                     in_transit=("status", lambda s: (s == "transit_censored").sum()),
                                     median_days_to_arrival=("days_to_arrival", "median")).round(0)
    add("")
    add(md_table(per.reset_index()))
    add("")
    sens = pd.read_csv(OUT / "arrival_sensitivity.csv", index_col=0)
    sp = sens["spread_days"].dropna()
    add(f"- Arrival-epoch spread across X in {{10,15,20,30}} km, K in {{14,30}} d: median {sp.median():.0f} d, "
        f"P90 {sp.quantile(.9):.0f} d, max {sp.max():.0f} d (n = {len(sp)} satellites arrived under at least one setting)")
    counts = {c: int(sens[c].notna().sum()) for c in sens.columns if c != "spread_days"}
    add("- Satellites classified as arrived per setting: " + ", ".join(f"{k} {v}" for k, v in counts.items()))
    add("")

    add("## 3.3 SGP4 prediction residuals (|position difference| vs the later element set, km)")
    res = pd.read_csv(OUT / "residual_summary.csv")
    rp = pd.read_csv(OUT / "residual_pairs.csv.gz", usecols=["NORAD_CAT_ID", "STATE"])
    nsat = rp.groupby("STATE")["NORAD_CAT_ID"].nunique()
    add(f"- Sample: {rp['NORAD_CAT_ID'].nunique()} satellites, {len(rp):,} residual pairs; satellites contributing per state: "
        + ", ".join(f"{k} {v}" for k, v in nsat.items()))
    rows = []
    for s in ["operational", "stranded", "drift", "ascent", "excursion"]:
        row = {"state": s, "satellites": int(nsat.get(s, 0))}
        for b in BINS:
            r = res[(res["STATE"] == s) & (res["age_bin"] == b)]
            row[f"{b} h median / P95 (n)"] = (f"{r['dr_p50'].iloc[0]:.3g} / {r['dr_p95'].iloc[0]:.3g} ({int(r['n'].iloc[0]):,})"
                                              if len(r) else "")
        rows.append(row)
    add("")
    add(md_table(pd.DataFrame(rows)))
    add("")

    add("## 3.4 Screening population (daily record)")
    P = pd.read_pickle(DATA / "pair_windows_daily.pkl.gz")
    first = P[P["t0"] == P["t0"].min()]
    add(f"- Daily windows: {P['t0'].nunique()} ({P['t0'].min():%Y-%m-%d} to {P['t0'].max():%Y-%m-%d}); first window has "
        f"{first['n_op'].iloc[0]} operational satellites in {first['n_planes'].iloc[0]} planes")
    add(f"- All operational inter-plane pair-windows: {len(P):,}; distinct pairs {P.groupby(['a', 'b']).ngroups:,}; events (<= 10 km) {int(P['obs10'].sum()):,}")
    ns = P[~P["std_angle"]]
    add(f"- Non-standard crossing angle (|gamma - k*{SPACING}| >= 2 deg): {len(ns):,} pair-windows "
        f"({100 * len(ns) / len(P):.1f}%), {int(ns['obs10'].sum())} events, of which on-grid and slow: {int(ns[ns['good']]['obs10'].sum())}")
    E = ns[ns["obs10"]]
    inv = (E["a"].str[:8] == "2024-185") | (E["b"].str[:8] == "2024-185")
    add(f"- Non-standard-angle events involving launch 2024-185: {int(inv.sum())} of {len(E)}")
    std = P[P["std_angle"]]
    add(f"- Standard-angle pair-windows: {len(std):,}; events {int(std['obs10'].sum()):,}")
    add(f"- Pair-windows with a satellite > 1 deg off grid: {100 * (P['slot_max'] > 1).mean():.1f}%; relative drift >= 50 km/day: "
        f"{100 * (P['drift'] >= 50).mean():.1f}%")
    G = P[P["std_angle"] & P["good"]]
    add(f"- Primary subset (standard angle, on-grid, slow): {len(G):,} pair-windows ({100 * len(G) / len(P):.1f}%), "
        f"{G.groupby(['a', 'b']).ngroups:,} distinct pairs, {int(G['obs10'].sum()):,} events")
    add(f"- Standard-angle criterion applied after the on-grid/slow criterion removes {int((P['good'] & ~P['std_angle']).sum()):,} "
        f"pair-windows and {int(P[P['good'] & ~P['std_angle']]['obs10'].sum())} events")

    (ROOT / "DATA_CLAIMS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
