"""Before/after table for the switch of slot errors from the equation-of-centre phase to SGP4 mean phase.

Before: ecphase_backup/pair_windows_daily.pkl.gz (slot errors from u_b = u - 2e sin(u - w)).
After:  data/pair_windows_daily.pkl.gz (slot errors from SGP4's mean argument of latitude; 11_per_angle.py rerun).
Same statistics code as 14_locked_claims.py. Writes PHASE_SWITCH.md.

Usage:  py 20_phase_switch_compare.py
"""
from __future__ import annotations

import importlib.util

import numpy as np
import pandas as pd

from common import DATA, ROOT

_spec = importlib.util.spec_from_file_location("lc", ROOT / "14_locked_claims.py")
lc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(lc)


def stats(P: pd.DataFrame) -> dict:
    P["t0"] = pd.to_datetime(P["t0"], utc=True)
    windows = sorted(P["t0"].unique())
    G = P[P["good"] & P["std_angle"]]
    k, n = int(G["obs10"].sum()), len(G)
    fr = np.array([0.005, 0.01, 0.015])
    pt = lc.share_at(G["nominal"].to_numpy(), G["obs10"].to_numpy(), fr)
    sh, _ = lc.block_boot(G, fr)
    lo, hi = np.percentile(sh[:, 1], [2.5, 97.5])
    early = G["t0"] < lc.EARLY_END
    ep = lc.episodes(G[G["obs10"]], windows)
    close = ep[ep["dmin"] < 3]
    e, o = 1000 * G[G["k"] % 2 == 0]["obs10"].mean(), 1000 * G[G["k"] % 2 == 1]["obs10"].mean()
    g2 = G[G["mod10"] | G["obs10"]]
    tp, fp, fn = int((g2["mod10"] & g2["obs10"]).sum()), int((g2["mod10"] & ~g2["obs10"]).sum()), int((~g2["mod10"] & g2["obs10"]).sum())
    return {
        "Primary pair-windows": f"{n:,}",
        "Events <= 10 km (primary)": f"{k:,}",
        "Event rate per 1000 (primary)": f"{1000 * k / n:.3f}",
        "Event rate early / recent": f"{1000 * G[early]['obs10'].mean():.3f} / {1000 * G[~early]['obs10'].mean():.3f}",
        "1% concentration (95% block bootstrap)": f"{pt[1]:.1%} ({lo:.1%}-{hi:.1%})",
        "1.5% concentration": f"{pt[2]:.1%}",
        "0.5% concentration": f"{pt[0]:.1%}",
        "1% concentration early / recent": " / ".join(
            f"{lc.share_at(X['nominal'].to_numpy(), X['obs10'].to_numpy(), [0.01])[0]:.1%}" for X in (G[early], G[~early])),
        "Even / odd rate per 1000 (ratio)": f"{e:.2f} / {o:.3f} ({e / o:.0f})",
        "Model recall / precision": f"{tp / (tp + fn):.1%} / {tp / (tp + fp):.1%}",
        "Episodes (distinct pairs)": f"{len(ep)} ({ep.groupby(['a', 'b']).ngroups})",
        "Episode duration median / P90 / max (d)": f"{ep['days'].median():.0f} / {ep['days'].quantile(.9):.0f} / {ep['days'].max()}",
        "Episodes >= 3 d with nominal margin < 100 km": f"{(ep[ep['days'] >= 3]['min_nominal'] < 100).mean():.1%}",
        "Episodes with d_min < 3 km": f"{len(close)}",
        "Median nominal margin of those episodes": f"{close['nominal_at_min'].median():.1f} km",
        "Share of those with nominal margin > 10 km / > 20 km": f"{(close['nominal_at_min'] > 10).mean():.0%} / {(close['nominal_at_min'] > 20).mean():.0%}",
        "Episodes remaining < 5 km after removing phase errors": f"{(ep['nominal_at_min'] < 5).mean():.0%}",
        "60 km point (share of events / share of pair-windows)": f"{(G['obs10'] & (G['nominal'] < 60)).sum() / k:.1%} / {(G['nominal'] < 60).mean():.2%}",
    }


def main():
    before = pd.read_pickle(ROOT / "ecphase_backup" / "pair_windows_daily.pkl.gz")
    after = pd.read_pickle(DATA / "pair_windows_daily.pkl.gz")
    A, B = stats(before), stats(after)
    lines = ["# Phase-variable switch: before / after (auto-generated by 20_phase_switch_compare.py)", "",
             "Before: slot errors in the equation-of-centre phase. After: slot errors in SGP4 mean argument of latitude. "
             "The crossing model, the SGP4 screen and the observed events are identical in both.", "",
             "| Quantity | Equation-of-centre phase | SGP4 mean phase |", "|---|---|---|"]
    lines += [f"| {q} | {A[q]} | {B[q]} |" for q in A]
    k = ["t0", "a", "b"]
    m = before[k + ["nominal", "good"]].merge(after[k + ["nominal", "good"]], on=k, suffixes=("_ec", "_sm"))
    small = m[m["nominal_ec"] < 200]
    d = (small["nominal_ec"] - small["nominal_sm"]).abs()
    lines += ["", f"- Pair-windows matched: {len(m):,} of {len(before):,} / {len(after):,}",
              f"- Nominal margin change where the margin is < 200 km: median {d.median():.2f} km, P90 {d.quantile(.9):.2f}, P99 {d.quantile(.99):.2f} (n = {len(small):,})",
              f"- On-grid/slow ('good') label changed for {(m['good_ec'] != m['good_sm']).mean():.2%} of pair-windows "
              f"({int((m['good_ec'] & ~m['good_sm']).sum()):,} left, {int((~m['good_ec'] & m['good_sm']).sum()):,} entered)"]
    (ROOT / "PHASE_SWITCH.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
