"""Section 7 Table 10 (event rate by nominal margin, observed vs window model vs single-Gaussian expectation) and
Figure 9 is now drawn by 26_fig9_panels.py (this script keeps Table 10).

Inputs: data/pair_windows_daily.pkl.gz (SGP4 mean phase). Outputs: MARGIN_TABLE.md.
Gaussian expectation: the along-track offset at the crossing ~ N(nominal, sigma_x), sigma_x = r * sigma_pair * cos(gamma/2),
sigma_pair = robust sigma of the pair phase deviation (same construction as 11_per_angle.py, part B).

Usage:  py 22_margin_table_fig.py
"""
from __future__ import annotations

import importlib.util

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import chi2, norm

from common import DATA, OUT, RE, ROOT, load_gp, satrec, to_jd

_spec = importlib.util.spec_from_file_location("lc", ROOT / "14_locked_claims.py")
lc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(lc)

EDGES = [0, 5, 10, 15, 20, 30, 40, 60, 100, 200, np.inf]
THR = 10.0
R_KM = RE + 1068.5
# validated categorical slots 1-3 (dataviz reference palette, light surface); aqua is < 3:1 contrast -> direct labels
C_POOLED, C_EARLY, C_RECENT = "#2a78d6", "#eb6834", "#1baf7a"
INK, INK2, SURFACE = "#0b0b0b", "#52514e", "#fcfcfb"
# three close curves: identity by legend + distinct line style (solid / dashed / dotted), not colour alone


def poisson(k, n):
    lo = chi2.ppf(0.025, 2 * k) / 2 if k else 0.0
    return 1000 * lo / n, 1000 * chi2.ppf(0.975, 2 * k + 2) / 2 / n


def table(G: pd.DataFrame) -> tuple[pd.DataFrame, float]:
    sig = 1.4826 * np.median(np.abs(G["slot_rel"] - np.median(G["slot_rel"])))
    sx = R_KM * np.radians(sig) * G["cosg2"]
    G = G.assign(p_gauss=norm.cdf((THR - G["nominal"]) / sx) - norm.cdf((-THR - G["nominal"]) / sx),
                 bin=pd.cut(G["nominal"], EDGES, right=False))
    rows = []
    for b, g in G.groupby("bin", observed=True):
        k, n = int(g["obs10"].sum()), len(g)
        lo, hi = poisson(k, n)
        m = int(g["mod10"].sum())
        mlo, mhi = poisson(m, n)
        rows.append(dict(nominal=str(b), pair_windows=n, events=k, rate=1000 * k / n, lo=lo, hi=hi,
                         model_events=m, model_rate=1000 * m / n, model_lo=mlo, model_hi=mhi,
                         gauss_rate=1000 * g["p_gauss"].mean()))
    return pd.DataFrame(rows), sig


def fmt(x):
    return f"{x:.3g}" if x < 10 else f"{x:.0f}"


def main():
    P = pd.read_pickle(DATA / "pair_windows_daily.pkl.gz")
    P["t0"] = pd.to_datetime(P["t0"], utc=True)
    G = P[P["good"] & P["std_angle"]].copy()
    T, sig = table(G)
    lines = ["# Table 10: event rate by nominal margin (auto-generated by 22_margin_table_fig.py)", "",
             f"Primary pair-windows (SGP4 mean phase): {len(G):,}; events {int(G['obs10'].sum())}. Rates per 1,000 pair-windows with "
             f"Poisson 95% intervals. Model = 24 h window minimum with observed phases <= 10 km. Gaussian = single-Gaussian pair "
             f"phase deviation, robust sigma {sig:.2f} deg.", "",
             "| Nominal margin | Pair-windows | Events | Observed rate (95%) | Model events | Model rate (95%) | Gaussian rate |",
             "|---|---|---|---|---|---|---|"]
    for r in T.itertuples():
        lines.append(f"| {r.nominal} | {r.pair_windows:,} | {r.events} | {fmt(r.rate)} ({fmt(r.lo)}-{fmt(r.hi)}) | {r.model_events} | "
                     f"{fmt(r.model_rate)} ({fmt(r.model_lo)}-{fmt(r.model_hi)}) | {fmt(r.gauss_rate)} |")
    ov = ((T["model_lo"] <= T["hi"]) & (T["model_hi"] >= T["lo"]))
    lines += ["", f"- Observed and model 95% intervals overlap in {int(ov.sum())} of {len(T)} classes"
              + ("" if ov.all() else f" (not: {', '.join(T.loc[~ov, 'nominal'])})")]
    gin = (T["gauss_rate"] >= T["lo"]) & (T["gauss_rate"] <= T["hi"])
    lines.append(f"- Gaussian expectation inside the observed 95% interval in {int(gin.sum())} of {len(T)} classes "
                 f"(outside: {', '.join(T.loc[~gin, 'nominal'])})")

    # ---------------- events at nominal margin >= 200 km: recompute each screened pass with the element sets nearest its TCA
    Xh = G[(G["nominal"] >= 200) & G["obs10"]]
    ev = pd.concat([pd.read_csv(OUT / f"encounters_{t}.csv") for t in ("dailyB", "dailyA")])
    ev["t0"] = pd.to_datetime(ev["t0"], utc=True, format="ISO8601")
    ev["tca"] = pd.to_datetime(ev["tca"], utc=True, format="ISO8601")
    ev = ev.assign(a=np.minimum(ev["OBJECT_ID_1"], ev["OBJECT_ID_2"]), b=np.maximum(ev["OBJECT_ID_1"], ev["OBJECT_ID_2"]))
    gp = load_gp(sorted((DATA / "gp_history_qianfan").glob("*.json.gz")))
    rec, npass = [], []
    for r in Xh.itertuples():
        e = ev[(ev["t0"] == r.t0) & (ev["a"] == r.a) & (ev["b"] == r.b)].sort_values("d_min_km")
        npass.append(len(e))
        e = e.iloc[0]
        pos = []
        for oid in (r.a, r.b):
            g = gp[gp["OBJECT_ID"] == oid]
            row = g.iloc[(g["EPOCH"] - e["tca"]).abs().argsort()[:1]].iloc[0]
            jd, frj = to_jd(e["tca"])
            pos.append(np.array(satrec(row).sgp4(jd[0], frj[0])[1]))
        rec.append(float(np.linalg.norm(pos[0] - pos[1])))
    rec = np.array(rec)
    big = rec > THR
    lines.append(f"- Events at nominal margin >= 200 km: {len(Xh)} ({len(Xh) / G['obs10'].sum():.1%} of events); window model predicts 0. "
                 f"Screened passes per event: {int((np.array(npass) == 1).sum())} single-pass. Window-centre model separation "
                 f"{Xh['d_now'].min():.0f}-{Xh['d_now'].max():.0f} km. Recomputed with the element sets nearest the time of closest approach: "
                 f"{int(big.sum())} exceed 10 km ({rec[big].min():.0f}-{rec[big].max():.0f} km: element-set updates within the window), "
                 f"{int((~big).sum())} stay <= 10 km (element sets at the window centre place the pair far apart). "
                 f"{int((Xh['t0'] >= pd.Timestamp('2026-07-01', tz='UTC')).sum())} of {len(Xh)} fall in July-September 2026.")

    # ---------------- Figure 9 is drawn by 26_fig9_panels.py (panel a: Table 10 by bin; panel b: concentration curve)
    cut = np.quantile(G["nominal"], 0.01)
    p1 = lc.share_at(G["nominal"].to_numpy(), G["obs10"].to_numpy(), [0.01])[0]
    lines.append(f"- Figure: out/fig9_concentration.png is drawn by 26_fig9_panels.py from this table and the concentration curve "
                 f"(1% cut at nominal margin {cut:.1f} km, pooled share {p1:.1%}; bands = 7-day block bootstrap 95%)")
    (ROOT / "MARGIN_TABLE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
