"""Section 8 counterfactual: observed configuration vs. the same pair-windows with observed phase deviations
removed (slot errors zeroed, all other elements -- a, e, i, RAAN, argument of perigee -- kept at their observed
values). The counterfactual distance at a window is exactly the nominal margin already computed for Sections 4-7
(05_planes.py / 11_per_angle.py), evaluated once at the window centre.

This is a centre-epoch counterfactual, not a second 24 h propagation: retaining each satellite's observed
semi-major axis means the two mean motions still differ (n_a != n_b) even at zero slot error, so a genuine
window-level counterfactual could still drift in relative phase away from the centre epoch, by the same
mechanism Section 5's observed-phase model uses (11_per_angle.py's window_arrays). That drift is not
re-propagated here; "counterfactual event" means the centre-epoch nominal margin is below 10 km, not a
counterfactual window minimum.

Quantities (primary pair-windows: on-grid, slowly drifting, standard angle -- same G as Table 10):
  - observed events (SGP4 screen, d_obs <= 10 km) vs counterfactual events (centre-epoch nominal margin < 10 km)
  - decomposition of observed events into inherent (nominal < 10 km: nominal geometry alone already crosses the
    threshold) and attributable (nominal >= 10 km: the observed phase deviation is what crosses the threshold)
  - decomposition of counterfactual events into realised (also an observed event) and averted (observed phase
    deviation moved the pair away from the counterfactual close approach)
  - same split before/after 1 April 2026, to see whether the 2026 rate rise (Section 7.5) survives the counterfactual
  - 7-day block-bootstrap 95% CIs on the attributable share and on the counterfactual/observed rate ratio

Writes COUNTERFACTUAL.md and out/fig10_counterfactual.png.

Usage:  py 23_counterfactual.py
"""
from __future__ import annotations

import importlib.util

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import chi2

from common import DATA, OUT, ROOT

_spec = importlib.util.spec_from_file_location("lc", ROOT / "14_locked_claims.py")
lc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(lc)

THR = 10.0
C_OBS, C_CF, C_INK2 = "#2a78d6", "#eb6834", "#52514e"
INK, SURFACE = "#0b0b0b", "#fcfcfb"


def poisson(k, n):
    lo = chi2.ppf(0.025, 2 * k) / 2 if k else 0.0
    return 1000 * lo / n, 1000 * chi2.ppf(0.975, 2 * k + 2) / 2 / n


def summarize(g: pd.DataFrame) -> dict:
    n = len(g)
    obs, cf = int(g["obs10"].sum()), int((g["nominal"] < THR).sum())
    inherent = int((g["obs10"] & (g["nominal"] < THR)).sum())
    attributable = obs - inherent
    averted = cf - inherent
    olo, ohi = poisson(obs, n)
    clo, chi = poisson(cf, n)
    return dict(n=n, obs=obs, obs_rate=1000 * obs / n, obs_lo=olo, obs_hi=ohi,
                cf=cf, cf_rate=1000 * cf / n, cf_lo=clo, cf_hi=chi,
                inherent=inherent, attributable=attributable, averted=averted,
                attributable_share=attributable / obs if obs else np.nan)


def block_boot(g: pd.DataFrame, nb: int = 500, block: int = 7, seed: int = 7) -> pd.DataFrame:
    days = sorted(g["t0"].unique())
    by = {d: d_g for d, d_g in g.groupby("t0")}
    rng = np.random.default_rng(seed)
    nblk = int(np.ceil(len(days) / block))
    rows = []
    for _ in range(nb):
        starts = rng.integers(0, max(len(days) - block, 1), nblk)
        sel = [days[s + j] for s in starts for j in range(block) if s + j < len(days)]
        gg = pd.concat([by[d] for d in sel], ignore_index=True)
        rows.append(summarize(gg))
    return pd.DataFrame(rows)


def ci(x: np.ndarray) -> str:
    lo, hi = np.nanpercentile(x, [2.5, 97.5])
    return f"{lo:.3g}-{hi:.3g}"


def main():
    P = pd.read_pickle(DATA / "pair_windows_daily.pkl.gz")
    P["t0"] = pd.to_datetime(P["t0"], utc=True)
    G = P[P["good"] & P["std_angle"]].copy()

    periods = [("Overall", G), ("Before April 2026", G[G["t0"] < lc.EARLY_END]), ("From April 2026", G[G["t0"] >= lc.EARLY_END])]
    lines = ["# Section 8 counterfactual (auto-generated by 23_counterfactual.py)", "",
              "Counterfactual: each pair-window's observed slot (phase) error is removed while a, e, i, RAAN and argument of "
              "perigee keep their observed values -- the counterfactual distance is the nominal margin used throughout Sections "
              "4-7, evaluated at the window centre (not re-propagated over the 24 h window; see the module docstring). Primary "
              "pair-windows only (on-grid, slowly drifting, standard angle).", "",
              "| Period | Pair-windows | Observed events (rate, 95%) | Counterfactual events (rate, 95%) | Inherent "
              "(both) | Attributable (observed only) | Averted (counterfactual only) | Attributable share of observed events |",
              "|---|---|---|---|---|---|---|---|"]
    boots = {}
    for name, g in periods:
        s = summarize(g)
        b = block_boot(g)
        boots[name] = b
        share_ci = ci(b["attributable_share"].to_numpy())
        lines.append(f"| {name} | {s['n']:,} | {s['obs']} ({s['obs_rate']:.3g}, {s['obs_lo']:.3g}-{s['obs_hi']:.3g}) | "
                     f"{s['cf']} ({s['cf_rate']:.3g}, {s['cf_lo']:.3g}-{s['cf_hi']:.3g}) | {s['inherent']} | {s['attributable']} | "
                     f"{s['averted']} | {s['attributable_share']:.1%} ({share_ci}) |")

    s_all = summarize(G)
    b_all = boots["Overall"]
    rate_ratio = s_all["cf_rate"] / s_all["obs_rate"]
    rr = (b_all["cf_rate"] / b_all["obs_rate"]).to_numpy()
    lines += ["", f"- Counterfactual/observed rate ratio: {rate_ratio:.3f} (bootstrap 95% {ci(rr)}) -- close to 1 despite the "
              f"per-window reshuffling, consistent with Section 6.4's finding that pair phase deviations show no net bias "
              f"toward or away from alignment.",
              f"- {s_all['attributable']} of {s_all['obs']} observed events ({s_all['attributable_share']:.1%}) occur at "
              f"pair-windows whose nominal margin is >= 10 km: the observed phase deviation reduces the reconstructed "
              f"separation sufficiently for the SGP4 screen to cross the 10 km threshold.",
              f"- {s_all['inherent']} of {s_all['obs']} observed events ({s_all['inherent'] / s_all['obs']:.1%}) occur at "
              f"pair-windows whose nominal margin is already < 10 km: the reconstructed nominal geometry places these pairs "
              f"within the event threshold even after the observed phase deviation is removed.",
              f"- {s_all['averted']} of {s_all['cf']} counterfactual events ({s_all['averted'] / s_all['cf']:.1%}) are not "
              f"observed events: at these pair-windows the observed phase deviation is associated with a larger separation "
              f"than the centre-epoch nominal geometry alone implies."]

    s_lo, s_hi = summarize(G[G["t0"] < lc.EARLY_END]), summarize(G[G["t0"] >= lc.EARLY_END])
    lines.append(f"- Attributable share before vs. from April 2026: {s_lo['attributable_share']:.1%} vs "
                 f"{s_hi['attributable_share']:.1%} -- the counterfactual (nominal-geometry-only) rate rose faster than the "
                 f"observed rate ({s_lo['cf_rate']:.3g} to {s_hi['cf_rate']:.3g} per 1,000, a {s_hi['cf_rate'] / s_lo['cf_rate']:.1f}x "
                 f"increase, vs {s_lo['obs_rate']:.3g} to {s_hi['obs_rate']:.3g}, a {s_hi['obs_rate'] / s_lo['obs_rate']:.1f}x increase). "
                 f"The decomposition therefore assigns a larger fraction of the 2026 rate increase to changes in reconstructed "
                 f"nominal geometry than to changes represented by the phase-deviation component. This is consistent with Section "
                 f"7.5's finding that the rise is a composition effect associated with the P1-P6 nominal margin collapsing (RISE_TEST.md), "
                 f"not a change in how phase deviations behave (Section 6).")

    # ---------------- Figure 10: observed vs nominal, quadrant scatter (nominal < 200 km for legibility)
    # x is symlog: linear from 0 to the 10 km threshold (where inherent and averted windows sit), logarithmic beyond it.
    # The diagonal y = x is the case in which the observed phase deviation makes no difference to the separation.
    Gs = G[G["nominal"] < 200].copy()
    rng = np.random.default_rng(3)
    keep = Gs["obs10"] | (Gs["nominal"] < THR) | (rng.random(len(Gs)) < 0.02)
    Gs = Gs[keep]
    ymax = min(200, Gs["d_obs"].quantile(0.995))
    fig, ax = plt.subplots(figsize=(7.6, 5.6), facecolor=SURFACE)
    ax.set_facecolor(SURFACE)
    inh = Gs["obs10"] & (Gs["nominal"] < THR)
    att = Gs["obs10"] & (Gs["nominal"] >= THR)
    ave = (~Gs["obs10"]) & (Gs["nominal"] < THR)
    bg = ~(inh | att | ave)
    kw = dict(lw=0, alpha=0.65)
    ax.scatter(Gs.loc[bg, "nominal"], Gs.loc[bg, "d_obs"], s=6, color="#c9c8c3", lw=0, alpha=0.6, label="Other pair-windows (2% sample)", zorder=1)
    ax.scatter(Gs.loc[ave, "nominal"], Gs.loc[ave, "d_obs"], s=12, color=C_CF, marker="^", label=f"Averted ({int(ave.sum()):,})", zorder=2, **kw)
    ax.scatter(Gs.loc[att, "nominal"], Gs.loc[att, "d_obs"], s=12, color=C_OBS, marker="s", label=f"Attributable ({int(att.sum()):,} plotted)", zorder=3, **kw)
    ax.scatter(Gs.loc[inh, "nominal"], Gs.loc[inh, "d_obs"], s=12, color=INK, marker="o", label=f"Inherent ({int(inh.sum()):,})", zorder=4, **kw)
    xs = np.linspace(0, ymax, 200)
    ax.plot(xs, xs, color=C_INK2, lw=1.0, zorder=5, label="Observed = nominal (no effect of phase deviation)")
    ax.axvline(THR, color=C_INK2, lw=0.8, ls=(0, (2, 2)))
    ax.axhline(THR, color=C_INK2, lw=0.8, ls=(0, (2, 2)))
    ax.set_xscale("symlog", linthresh=THR, linscale=1.6, base=10)
    ax.set_xlim(0, 200)
    ax.set_xticks([0, 2, 4, 6, 8, 10, 20, 50, 100, 200])
    ax.set_xticklabels(["0", "2", "4", "6", "8", "10", "20", "50", "100", "200"])
    ax.minorticks_off()
    ax.set_ylim(0, ymax)
    ax.set_xlabel("Centre-epoch nominal margin (counterfactual, km; linear to 10 km, logarithmic beyond)", color=C_INK2, fontsize=9)
    ax.set_ylabel("Observed SGP4-screen minimum distance (km)", color=C_INK2, fontsize=9)
    leg = ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=2, frameon=False, fontsize=8.5)
    for t in leg.get_texts():
        t.set_color(C_INK2)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)
    for s in ("left", "bottom"):
        ax.spines[s].set_color("#c9c8c3")
    ax.tick_params(colors=C_INK2, labelsize=8.5)
    ax.set_title("Observed vs. centre-epoch counterfactual (slot errors removed) minimum distance", fontsize=10, color=INK, loc="left")
    fig.tight_layout()
    fig.savefig(OUT / "fig10_counterfactual.png", dpi=200, facecolor=SURFACE, bbox_inches="tight")
    lines.append(f"- Figure: out/fig10_counterfactual.png (pair-windows with nominal margin < 200 km, excludes the 22 "
                 f"attributable events with nominal margin >= 200 km examined in Section 7.3; other pair-windows are a 2% random sample "
                 f"of the remainder for context; dashed lines mark the 10 km threshold on each axis; the solid diagonal is observed = nominal; "
                 f"the x-axis is linear to 10 km and logarithmic beyond; the y-axis is cut at {ymax:.1f} km, so averted markers above it "
                 f"are not drawn)")

    (ROOT / "COUNTERFACTUAL.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
