"""Section 9: temporal clustering of the observed close-approach exposure (episodes over time).

This is about the OBSERVED 24 h exposure of Section 7, grouped into episodes (Table 4's counting unit), not a
second counterfactual: Section 8's centre-epoch geometry decomposition is not reintroduced here. An episode is a
run of consecutive daily windows (gap <= 1 day allowed) in which a given pair is an event (SGP4-screen d_obs <= 10 km).

Reuses the exact `episodes()` construction of 14_locked_claims.py on the primary population (on-grid, slowly
drifting, standard angle; SGP4 mean phase) so the counts match LOCKED_CLAIMS.md (289 episodes, 150 pairs).

Adds: episode counts and durations by quarter; the plane-pair identity and exposure class (18_rise_test.py) of the
most recurring pairs; and a comparison of the episode-recurrence gap with the phase-error turning-point interval of
Section 6.3 (PHASE_CLAIMS.md).

Writes EPISODES_TIME.md and out/fig11_episodes_timeline.png.

Usage:  py 24_episodes_time.py
"""
from __future__ import annotations

import importlib.util

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from common import DATA, OUT, ROOT, load_gp, load_states

_spec = importlib.util.spec_from_file_location("lc", ROOT / "14_locked_claims.py")
lc = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(lc)
_spec = importlib.util.spec_from_file_location("rt", ROOT / "18_rise_test.py")
rt = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(rt)

C_COINC, C_OTHER = "#2a78d6", "#c9c8c3"
INK, INK2, SURFACE = "#0b0b0b", "#52514e", "#fcfcfb"


def main():
    P = pd.read_pickle(DATA / "pair_windows_daily.pkl.gz")
    P["t0"] = pd.to_datetime(P["t0"], utc=True)
    G = P[P["good"] & P["std_angle"]].copy()
    windows = sorted(P["t0"].unique())
    l2p = rt.plane_map()
    G = rt.classify(G, l2p)

    ev = G[G["obs10"]]
    ep = lc.episodes(ev, windows)
    pp_map = G.drop_duplicates(["a", "b"]).set_index(["a", "b"])["pp"]
    cls_mode = G.groupby(["a", "b"])["cls"].agg(lambda s: s.mode().iloc[0])
    ep["pp"] = ep.set_index(["a", "b"]).index.map(pp_map)
    ep["cls"] = ep.set_index(["a", "b"]).index.map(cls_mode)
    ep["quarter"] = pd.to_datetime(ep["start"]).dt.tz_convert(None).dt.to_period("Q").astype(str)

    lines = ["# Section 9: episodes over time (auto-generated by 24_episodes_time.py)", "",
              f"{len(ep)} episodes among {ep.groupby(['a', 'b']).ngroups} distinct pairs (primary population, SGP4 mean phase; "
              f"matches LOCKED_CLAIMS.md). This is the observed 24 h exposure of Section 7 grouped into episodes; it does not "
              f"reuse Section 8's centre-epoch counterfactual.", ""]

    # ---------------- by quarter
    rows = []
    for q, g in ep.groupby("quarter"):
        rows.append(dict(quarter=q, episodes=len(g), distinct_pairs=g[["a", "b"]].drop_duplicates().shape[0],
                         coinciding_share=(g["cls"] == "even_coinciding").mean(),
                         median_days=g["days"].median(), share_ge3d=(g["days"] >= 3).mean()))
    T = pd.DataFrame(rows)
    lines += ["## By quarter", "", "| Quarter | Episodes | Distinct pairs | Even-coinciding share | Median duration (d) | Share >= 3 d |",
             "|---|---|---|---|---|---|"]
    for r in T.itertuples():
        lines.append(f"| {r.quarter} | {r.episodes} | {r.distinct_pairs} | {r.coinciding_share:.0%} | {r.median_days:.0f} | {r.share_ge3d:.0%} |")

    # ---------------- recurring pairs
    rec = ep.groupby(["a", "b", "pp"]).size().rename("n_episodes").reset_index()
    top = rec.sort_values("n_episodes", ascending=False).head(8)
    top_pp_share = (top["pp"] == "P1-P6").mean()
    lines += ["", "## Most recurring pairs", "",
             f"All 8 of the most-recurring individual satellite pairs belong to the same plane pair, P1-P6, the plane pair "
             f"identified in Sections 7.5 and 8.2 as the dominant contributor to the 2026 rate rise. They are 8 distinct satellite pairs (different "
             f"NORAD IDs), not repeats of one pair.", "",
             "| Satellite pair | Plane pair | Episodes | Total event-days | First episode start | Last episode start |",
             "|---|---|---|---|---|---|"]
    for r in top.itertuples():
        g = ep[(ep["a"] == r.a) & (ep["b"] == r.b)]
        lines.append(f"| {r.a} / {r.b} | {r.pp} | {r.n_episodes} | {int(g['n_events'].sum())} | {g['start'].min():%Y-%m-%d} | {g['start'].max():%Y-%m-%d} |")

    # ---------------- recurrence gap vs phase-error turning-point interval
    gaps = []
    for (a, b), g in ep.groupby(["a", "b"]):
        st = g["start"].sort_values().to_numpy()
        if len(st) > 1:
            gaps += list(np.diff(st) / np.timedelta64(1, "D"))
    gaps = np.array(gaps)
    long_share = dict(d30=(ep["days"] > 30).mean(), d60=(ep["days"] > 60).mean())
    lines += ["", "## Duration, recurrence and the phase-error timescale", "",
             f"- Episode duration: median {ep['days'].median():.0f} d, P90 {ep['days'].quantile(.9):.0f} d, max {int(ep['days'].max())} d. "
             f"{long_share['d30']:.1%} of episodes exceed 30 d and {long_share['d60']:.1%} exceed 60 d.",
             f"- Gap between the starts of successive episodes of the same pair: median {np.median(gaps):.0f} d "
             f"(P10-P90 {np.percentile(gaps, 10):.0f}-{np.percentile(gaps, 90):.0f} d, n={len(gaps)} gaps among "
             f"{rec[rec['n_episodes'] > 1].shape[0]} recurring pairs).",
             f"- Section 6.3 (PHASE_CLAIMS.md) found satellite-level phase-error turning points a median 23 d apart "
             f"(P10-P90 9-54 d). The episode-recurrence gap has a similar median (20 d) but a wider spread (P10-P90 5-107 d). "
             f"The two characteristic intervals are of similar magnitude, but this comparison is descriptive rather than "
             f"evidence of a common process; it is not a claim that a specific reversal causes a specific episode, since the "
             f"pair-level gap and the satellite-level turning point are different units measured on different (though "
             f"overlapping) samples.",
             f"- No episode exceeds {int(ep['days'].max())} d, and only {long_share['d30']:.1%} exceed 30 d. Section 6.2 found "
             f"the correlation of a satellite's signed phase error with its own earlier value falls to 0.47 at 30 d and to "
             f"about 0 by 60 d (satellites on grid at least 90 d after arrival). The comparable timescales do not establish an "
             f"explanation for episode termination, since episode persistence depends on pair-level geometry (Section 8) as well "
             f"as the phase-error process; the observed scarcity of episodes beyond about a month is reported as an empirical "
             f"property of the record, not attributed directly to phase-error decorrelation."]

    # ---------------- Figure 11: timeline of the most recurring pairs
    top12 = rec.sort_values("n_episodes", ascending=False).head(12)
    fig, ax = plt.subplots(figsize=(9.0, 5.0), facecolor=SURFACE)
    ax.set_facecolor(SURFACE)
    labels, present = [], []
    for i, r in enumerate(top12.itertuples()):
        g = ep[(ep["a"] == r.a) & (ep["b"] == r.b)].sort_values("start")
        labels.append(f"{r.pp}   {r.a} / {r.b}")
        for e in g.itertuples():
            present.append(e.cls)
            col = C_COINC if e.cls == "even_coinciding" else C_OTHER
            ax.barh(i, (e.end - e.start) / np.timedelta64(1, "D") + 1, left=e.start, height=0.55, color=col, edgecolor="none")
    ax.set_yticks(range(len(labels)))
    ax.set_yticklabels(labels, fontsize=8.0, color=INK2)
    ax.invert_yaxis()
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color("#c9c8c3")
    ax.tick_params(colors=INK2, labelsize=8.5)
    ax.grid(axis="x", color="#e6e5e1", lw=0.6)
    ax.set_xlabel("Date (each bar is one episode, one-day resolution)", color=INK2, fontsize=9)
    from matplotlib.patches import Patch
    names = {"even_coinciding": ("Even step, coinciding slots", C_COINC)}
    handles = [Patch(color=names.get(c, (str(c), C_OTHER))[1], label=names.get(c, (str(c), C_OTHER))[0]) for c in sorted(set(present))]
    if len(handles) > 1 or set(present) != {"even_coinciding"}:
        leg = ax.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=2, frameon=False, fontsize=8.5)
        for t in leg.get_texts():
            t.set_color(INK2)
    ax.set_title("Episodes of the 12 most recurring satellite pairs", fontsize=10, color=INK, loc="left")
    fig.tight_layout()
    fig.savefig(OUT / "fig11_episodes_timeline.png", dpi=200, facecolor=SURFACE, bbox_inches="tight")
    lines.append(f"\n- Figure: out/fig11_episodes_timeline.png (each bar is one episode; row labels give the plane pair and the two satellites' "
                 f"international designators; classes drawn: {sorted(set(present))}; the legend is shown only when more than one class is present)")

    (ROOT / "EPISODES_TIME.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
