"""Assemble the public release tree in release/ from an explicit allow-list, and check it.  No analysis is run.

Policy (manuscript Section 12): the release contains the code, the query specification, derived tables and the figures; it contains no Space-Track element
sets in any form, no per-satellite per-epoch element table, and no credentials. Everything is copied from an allow-list; the rest is left out, with the reason
recorded in RELEASE_MANIFEST.md.

Checks made on the staged tree (any failure gives exit status 1)
  1. nothing on the forbidden list is present (.env, data/, pickles, gp_history/satcat/background files, per-pass and per-element-set tables);
  2. the Space-Track credentials, if a .env file exists, do not appear in any released file (their values are compared in memory and never printed);
  3. no released CSV carries raw element-set columns (mean motion, eccentricity, RAAN, mean anomaly, ... as a per-object table);
  4. every script in the tree compiles;
  5. every file named in the README figure table exists in the tree.

Usage:  py 32_build_release.py
"""
from __future__ import annotations

import hashlib
import py_compile
import re
import shutil
import sys
from fnmatch import fnmatch
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REL = ROOT / "release"

TOP_FILES = ["README.md", "QUERY_SPEC.md", "LICENSE", "LICENSE-DATA.md", "CITATION.cff", "requirements.txt", ".gitignore",
             "BANDWIDTH_CHECK.md", "COUNTERFACTUAL.md", "DATA_CLAIMS.md", "EPISODES_TIME.md", "GEOMETRY_CLAIMS.md", "LOCKED_CLAIMS.md",
             "MARGIN_TABLE.md", "PHASE_CLAIMS.md", "PHASE_SWITCH.md", "RISE_TEST.md", "SIGNED_DEVIATION.md",
             "FIG123_NUMBERS.md", "FIG456_NUMBERS.md", "FIG7_MODEL.md", "FIG8_TRAJECTORIES.md", "FIG9_PANELS.md"]
OUT_PATTERNS = ["fig[0-9]*.png", "figA1_*.png",
                "arrival_sensitivity.csv", "cadence.csv", "coherence_scan.csv", "crossing_model_pairs.csv",
                "encounter_pairs_3d.csv", "encounter_pairs_14d.csv", "encounter_pairs_daily.csv", "encounter_pairs_dailyA.csv", "encounter_pairs_dailyB.csv",
                "episodes.csv", "episodes_dailyA.csv", "fig8_picks.csv",
                "final_pair_table.csv", "final_planes.csv", "geometry_snapshot_offsets.csv", "geometry_snapshots.csv", "ideal_vs_observed_pairs.csv",
                "model_vs_sgp4_pairs.csv", "per_angle_*.csv", "per_margin*.csv", "per_quarter*.csv", "phase_migrations.csv", "phase_turning_points.csv",
                "residual_summary.csv", "satellite_summary*.csv", "sensitivity.csv"]
EXCLUDED = [
    (".env", "credentials"),
    ("data/", "Space-Track element sets and pickles built from them (Space-Track terms)"),
    ("ecphase_backup/*.pkl.gz", "pair-window pickles of the superseded equation-of-centre run"),
    ("out/residual_pairs.csv.gz", "per-element-set residual pairs"),
    ("out/encounters_*.csv", "per-pass encounter dumps (large; regenerated by 04_screen.py); includes the stale pilot 30-day encounters_daily.csv"),
    ("out/*_bg.csv, out/log_screen_bg.txt", "pilot screen against other catalogued objects (not part of the Qianfan-only analysis)"),
    ("out/pilot_numbers.json, out/polar_pairs_per_epoch.csv", "pilot outputs of 06_figures.py"),
    ("out/encounter_rates_*.csv, out/episodes_by_quarter.csv", "pilot per-state rates and quarter table (no downstream reader; superseded by EPISODES_TIME.md)"),
    ("out/episode_prediction.csv, out/episode_series.csv", "outputs of the dropped drift-extrapolation check (09_model_checks.py part B), not used in the paper"),
    ("out/altitude/", "pilot per-launch altitude plots (Fig. 2 replaces them)"),
    ("out/log_*", "run logs"),
    ("HANDOFF.md, SESSION_LOG_*.md, FINDINGS.md, PAPER_OUTLINE.md, LITERATURE.md, README_pilot.md, FIGURE_AUDIT.md, FIGURE_CAPTIONS.md, manuscript/",
     "working notes and manuscript drafts"),
    ("__pycache__/", "caches"),
]
FORBIDDEN_NAMES = ["*.pkl", "*.pkl.gz", ".env", "final_satellites*", "residual_pairs*", "*gp_history*", "*satcat*", "*background_snapshot*",
                   "encounters_*.csv", "*_bg.csv", "pilot_numbers.json"]
RAW_ELEMENT_COLUMNS = {"MEAN_MOTION", "ECCENTRICITY", "INCLINATION", "RA_OF_ASC_NODE", "ARG_OF_PERICENTER", "MEAN_ANOMALY", "BSTAR",
                       "MEAN_MOTION_DOT", "MEAN_MOTION_DDOT", "EPOCH", "CREATION_DATE", "GP_ID"}
fails: list[str] = []


def fail(msg):
    fails.append(msg)
    print("FAIL:", msg)


def copy(src: Path, dst: Path):
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def main():
    if REL.exists():                      # keep a git repository inside release/ (its .git directory) if there is one
        for child in REL.iterdir():
            if child.name == ".git":
                continue
            shutil.rmtree(child) if child.is_dir() else child.unlink()
    REL.mkdir(exist_ok=True)
    for p in sorted(ROOT.glob("*.py")):
        copy(p, REL / p.name)
    for n in TOP_FILES:
        if (ROOT / n).exists():
            copy(ROOT / n, REL / n)
        else:
            fail(f"allow-listed file missing: {n}")
    for p in sorted((ROOT / "out").iterdir()):
        if p.is_file() and any(fnmatch(p.name, pat) for pat in OUT_PATTERNS):
            copy(p, REL / "out" / p.name)
    sup = ROOT / "out" / "superseded"
    if sup.exists():
        for p in sorted(sup.iterdir()):
            copy(p, REL / "out" / "superseded" / p.name)
    for p in sorted((ROOT / "ecphase_backup").glob("*.md")):
        copy(p, REL / "out" / "superseded" / "ecphase_outputs" / p.name)
    (REL / "out" / "superseded" / "ecphase_outputs" / "README.md").write_text(
        "Result files of the run in the equation-of-centre phase variable, replaced on 2026-09-25 by the run in SGP4's mean argument of latitude "
        "(see PHASE_SWITCH.md). Superseded; not valid for the manuscript.\n", encoding="utf-8")

    files = sorted(p for p in REL.rglob("*") if p.is_file() and p.name != "RELEASE_MANIFEST.md" and ".git" not in p.relative_to(REL).parts)
    # 1. forbidden names
    for p in files:
        for pat in FORBIDDEN_NAMES:
            if fnmatch(p.name, pat):
                fail(f"forbidden file in the release: {p.relative_to(REL)}")
    # 2. credentials
    secrets = []
    env = ROOT / ".env"
    if env.exists():
        for line in env.read_text(encoding="utf-8", errors="ignore").splitlines():
            if "=" in line and not line.strip().startswith("#"):
                v = line.split("=", 1)[1].strip().strip("'\"")
                if len(v) >= 4:
                    secrets.append(v)
    hits = 0
    for p in files:
        if p.suffix.lower() in {".png", ".gz"}:
            continue
        t = p.read_text(encoding="utf-8", errors="ignore")
        if any(s in t for s in secrets):
            hits += 1
            fail(f"a credential value appears in {p.relative_to(REL)}")
    # 3. raw element columns in CSVs
    for p in files:
        if p.suffix == ".csv":
            head = p.read_text(encoding="utf-8", errors="ignore").split("\n", 1)[0].split(",")
            bad = RAW_ELEMENT_COLUMNS & set(head)
            if len(bad) >= 2:
                fail(f"{p.relative_to(REL)} has raw element-set columns: {sorted(bad)}")
    # 4. compile
    for p in sorted(REL.glob("*.py")):
        try:
            py_compile.compile(str(p), cfile=str(REL / "__compiled_check.pyc"), doraise=True)
        except py_compile.PyCompileError as e:
            fail(f"does not compile: {p.name}: {e}")
    (REL / "__compiled_check.pyc").unlink(missing_ok=True)
    # 5. README figure table
    readme = (REL / "README.md").read_text(encoding="utf-8")
    for f in re.findall(r"`(out/fig[0-9A]\w*\.png)`", readme):
        if not (REL / f).exists():
            fail(f"README names {f}, which is not in the release")

    files = sorted(p for p in REL.rglob("*") if p.is_file() and p.name != "RELEASE_MANIFEST.md" and ".git" not in p.relative_to(REL).parts)
    total = sum(p.stat().st_size for p in files)
    lines = ["# Release manifest", "", f"{len(files)} files, {total / 1e6:.1f} MB. Built by `32_build_release.py`.", "",
             "## Left out on purpose", "", "| Path | Reason |", "|---|---|"]
    lines += [f"| {a} | {b} |" for a, b in EXCLUDED]
    lines += ["", "## Checks", "", f"- credential values searched for in all text files: {len(secrets)} value(s) taken from .env, {hits} file(s) containing one",
              "- raw element-set columns in released CSV files: none" if not any("raw element" in f for f in fails) else "- raw element-set columns: FOUND (see failures)",
              "- forbidden-name scan, script compilation and README figure-table check run on the staged tree",
              "", "## Files (SHA-256)", "", "| File | Bytes | SHA-256 |", "|---|---|---|"]
    for p in files:
        lines.append(f"| {p.relative_to(REL).as_posix()} | {p.stat().st_size} | {hashlib.sha256(p.read_bytes()).hexdigest()[:16]}... |")
    (REL / "RELEASE_MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"release tree: {len(files)} files, {total / 1e6:.1f} MB; secrets checked: {len(secrets)}")
    print("RESULT:", "all checks passed" if not fails else f"{len(fails)} problem(s)")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
